create table if not exists game
(
    id                 bigint generated by default as identity
        primary key,
    board              oid,
    board_size         integer not null,
    created_date       timestamp(6),
    is_deleted         boolean not null,
    is_game_over       boolean not null,
    is_player2computer boolean not null,
    is_single_player   boolean not null,
    player1symbol      varchar(255),
    player2symbol      varchar(255),
    updated_date       timestamp(6),
    win_streak         integer not null,
    winner             varchar(255)
);


